import type { DarkTombPocketSource } from "./types.js";

/**
 * A structurally complete, deliberately non-canon starter for the Book II
 * grammar. Authors replace its particulars; the contract and causal order stay.
 */
export const DARK_TOMB_STARTER: DarkTombPocketSource = {
  format: "dark-tomb-pocket/1",
  identity: {
    id: "untitled-dark-tomb",
    title: "Untitled Dark Tomb",
    description: "A private-branch authoring seed for an inhabited place whose survival depends on remaining misclassified.",
    author: "Creator",
    version: "0.1.0",
    estimatedCycles: 8,
    parentCanons: [
      "The Godscar Codex, Book I: The Open Universe · first recension",
      "The Godscar Codex, Book II: The Dark Tomb · first recension",
    ],
    canonRelation: "private-branch",
  },
  controlQuestion: "When the supposedly empty place is revealed as inhabited, which map changes, who certified the old absence, and what power depended on the misclassification?",
  pressures: [
    {
      kind: "tomb-form",
      id: "buried-district",
      label: "Buried district",
      description: "A common-depths neighborhood survives beneath a ruin whose exterior profile has ended every serious survey.",
    },
    {
      kind: "exterior-lie",
      id: "dead-ruin",
      label: "Dead ruin",
      description: "The outside is supplied with a complete explanation: the site failed, emptied, and no longer supports complex life.",
    },
    {
      kind: "custodian",
      id: "wakekeeper-council",
      label: "Wakekeeper council",
      description: "A council controls threat models, maps, routes, and the signature allocations that sustain the exterior lie.",
    },
    {
      kind: "ordinary-good",
      id: "district-clinic",
      label: "District clinic",
      description: "A clinic keeps identifiable residents alive and consumes heat, power, medicine, and movement the Alarm can restrict.",
    },
    {
      kind: "excluded-actor",
      id: "sealed-neighborhood",
      label: "The sealed neighborhood",
      description: "A population omitted by the official map survives in a layer whose recognition would change jurisdiction and resource claims.",
    },
    {
      kind: "approaching-breach",
      id: "overhead-scan",
      label: "Overhead scan",
      description: "An ambiguous observer begins classifying the grave skin while the tomb's own wake becomes harder to contain.",
    },
    {
      kind: "cost-of-opening-or-closing",
      id: "exposure-or-death",
      label: "Exposure or immediate death",
      description: "Opening may expose the civilization; closing the clinic and route will kill people whose names are already known.",
    },
    {
      kind: "scale-revelation",
      id: "ruin-is-inhabited",
      label: "The ruin is a political geography",
      description: "The apparently dead site is one node in a wider map of inhabited absences, partial routes, and managed recognition.",
    },
  ],
  evidence: {
    tier: "contested-canon",
    claim: "The exterior anomaly is an observer classifying the grave skin rather than a failure produced entirely by the tomb's own neglected systems.",
    venue: "A joint Seal Court, Witness House, and district assembly",
    legitimacyTarget: "The Wakekeeper council's exclusive authority to declare Hush and erase routes",
    upsideIfAccepted: "The tomb can negotiate a bounded opening, preserve the clinic, and recognize the omitted district before the observer completes its classification.",
    downsideIfAccepted: "The investigation itself makes routes, populations, and capabilities transferable to actors outside the protected map.",
    failureIfFalse: "A mistaken opening spends the tomb's visibility on a threat that was never a witness or rescuer.",
    receipts: [
      {
        id: "wake-anomaly",
        label: "Wake anomaly record",
        source: "Quiet-works sensors, surface observations, and archived Alarm comparisons",
        intervention: "Maintainers increased sensor resolution and briefly redirected heat to distinguish an outside signal from internal failure.",
        limits: "The intervention changed the signature being measured and cannot establish the observer's intention.",
      },
    ],
  },
  factionReceipts: [
    {
      factionId: "wakekeeper-council",
      factionName: "Wakekeeper Council",
      variableControlled: "visibility",
      publicGood: "It keeps the exterior lie credible, coordinates Alarm phases, and prevents identifiable detection events.",
      characteristicFailure: "Its threat model can convert medicine, movement, knowledge, and dissent into permanent signature violations.",
    },
    {
      factionId: "maintainer-guild",
      factionName: "Buried Commons Guild",
      variableControlled: "infrastructure truth",
      publicGood: "It keeps air, water, heat, waste, and the clinic operating across political boundaries.",
      characteristicFailure: "Technical indispensability can become an unreviewable veto over every district that depends on shared systems.",
    },
    {
      factionId: "opening-assembly",
      factionName: "Opening Assembly",
      variableControlled: "recognition",
      publicGood: "It restores evidence, routes, kinship, and citizenship to people the official map calls absent.",
      characteristicFailure: "Its demand for visibility can assign extinction risk to residents and surface castes who did not choose contact.",
    },
  ],
  cast: [
    {
      id: "mara-ven",
      name: "Mara Ven",
      roleId: "wakekeeper",
      responsibility: "depends-on-alarm",
      description: "A Wakekeeper whose authority and family safety both depend on the current Alarm remaining credible.",
      factionId: "wakekeeper-council",
    },
    {
      id: "lio-saren",
      name: "Lio Saren",
      roleId: "surface-bearer",
      responsibility: "bears-cost-of-concealment",
      description: "A surface worker whose community absorbs inspection, deprivation, and first-contact risk for deeper districts.",
      factionId: "opening-assembly",
    },
    {
      id: "tess-oro",
      name: "Tess Oro",
      roleId: "maintainer",
      responsibility: "understands-quiet-works",
      description: "A heat and air maintainer who knows which redundancies are real and which scarcity claims are politically manufactured.",
      factionId: "maintainer-guild",
    },
    {
      id: "cael-ith",
      name: "Cael Ith",
      roleId: "interlocutor",
      responsibility: "translates-excluded-actor",
      description: "A route listener able to translate the pressure code used by the neighborhood erased during an ancient Cut.",
      factionId: "opening-assembly",
    },
    {
      id: "aster-ren",
      name: "Aster Ren",
      roleId: "witness",
      responsibility: "holds-map-changing-evidence",
      description: "A Witness House archivist carrying the only receipt that links the current exterior anomaly to prior Overhead events.",
      factionId: "opening-assembly",
    },
    {
      id: "iri-vale",
      name: "Iri Vale",
      roleId: "deliberator",
      responsibility: "benefits-from-delay",
      description: "A Seal Court advocate whose institution gains authority while evidence remains insufficient for either opening or closure.",
      factionId: "wakekeeper-council",
    },
    {
      id: "nacre-nine",
      name: "Nacre Nine",
      roleId: "exception",
      responsibility: "sovereign-exception",
      description: "An illegal child recognized by an old door as a jurisdiction the current threat model says cannot exist.",
      factionId: "opening-assembly",
    },
  ],
  anatomy: [
    {
      kind: "grave-skin",
      label: "The ruin field",
      description: "Collapsed structures and a hazardous profile absorb outside inspection.",
      currentUse: "Surface families, decoy maintenance, and first-contact observation",
      inheritedPurpose: "The visible remains of the failure that produced burial",
      officialClassification: "Dead industrial ruin",
    },
    {
      kind: "shroud",
      label: "The false weather",
      description: "Counterfeit emissions, staged decay, and sacrificial routes sustain the dead-ruin account.",
      currentUse: "Observer management and surface agriculture",
      inheritedPurpose: "Emergency camouflage assembled during the first Alarm",
      officialClassification: "Natural corrosion and unstable atmosphere",
    },
    {
      kind: "quiet-works",
      label: "The buried commons",
      description: "Heat sinks, reservoirs, filters, relays, and waste loops make absence physically plausible.",
      currentUse: "Life support, wake management, and illicit district bypasses",
      inheritedPurpose: "Concealment infrastructure and evacuation support",
      officialClassification: "Uninhabited utility volume",
    },
    {
      kind: "common-depths",
      label: "The lamp district",
      description: "Homes, school, clinic, market, kitchens, workshops, and public life make the tomb a civilization.",
      currentUse: "Ordinary civic and domestic life",
      inheritedPurpose: "A temporary shelter converted into a permanent neighborhood",
      officialClassification: "No recognized population",
    },
    {
      kind: "custodial-ring",
      label: "The Seal Court",
      description: "Maps, sensors, archives, credentials, routes, and Alarm authority are partitioned here.",
      currentUse: "Government, audit, and signature allocation",
      inheritedPurpose: "Emergency command and threat classification",
      officialClassification: "Restricted municipal administration",
    },
    {
      kind: "war-layer",
      label: "The cut transit ring",
      description: "Old defenses, target logic, sealed routes, and an omitted district preserve the original crisis.",
      currentUse: "Salvage frontier and isolated habitation",
      inheritedPurpose: "Military transit and sacrificial compartmentalization",
      officialClassification: "Collapsed and empty",
    },
    {
      kind: "black-core",
      label: "The first witness chamber",
      description: "The present order cannot safely reveal what the original Alarm recorded or whom it sacrificed.",
      currentUse: "Unknown until the final descent",
      inheritedPurpose: "Certification of the threat and authority to end the Alarm",
      officialClassification: "Nonexistent",
    },
  ],
  depths: [
    {
      kind: "material",
      description: "Seals, pressure, structural collapse, and environmental barriers separate the district from the war layer.",
      barrier: "A failed transit ring and incompatible atmosphere",
      beneficiary: "The custodians who can describe every inaccessible place as physically unreachable",
    },
    {
      kind: "signal",
      description: "Heat, traffic, communication, and movement are transformed before they reach the grave skin.",
      barrier: "The shroud and the limited safe-release calendar",
      beneficiary: "The offices that allocate wake and private light",
    },
    {
      kind: "administrative",
      description: "Credentials, taboos, and jurisdictions determine which recognized identity may cross each threshold.",
      barrier: "Seal Court permissions and dead military identities",
      beneficiary: "The authorities able to treat unauthorized life as a security incident",
    },
    {
      kind: "historical",
      description: "Collapsed orders and erased populations separate present use from the layer's original purpose.",
      barrier: "An ancient Cut and a revised public history",
      beneficiary: "The government whose legitimacy depends on the omission remaining complete",
    },
    {
      kind: "interpretive",
      description: "The ruin classification prevents observers and residents from recognizing the political geography already present.",
      barrier: "A complete story explaining why no one could be alive there",
      beneficiary: "Every institution whose authority begins after the certified absence",
    },
  ],
  signatureBudget: {
    observer: "An unidentified vessel or sensor regime above the grave skin",
    exteriorClassification: "Dead industrial ruin with unstable natural emissions",
    wakeSources: ["clinic heat", "air circulation", "public light", "route traffic", "birth and food demand", "archival transmission"],
    operations: [
      { kind: "sink", description: "Store heat and waste until a safe release window.", cost: "Reservoirs fill and districts inherit deferred failure." },
      { kind: "spread", description: "Distribute emissions across the ruin field and long time spans.", cost: "Coordination expands custodial reach across otherwise independent districts." },
      { kind: "shift", description: "Move wake into exposed radiators and sacrificial routes.", cost: "Remote workers and surface families bear concentrated danger." },
      { kind: "mask", description: "Embed inhabited activity inside plausible weather and corrosion.", cost: "The tomb becomes dependent on environmental processes it cannot fully control." },
      { kind: "counterfeit", description: "Present the wake as a failing reactor and automated ruin cycle.", cost: "The observer model must remain believable and can turn genuine rescue away." },
      { kind: "sacrifice", description: "Permit a visible layer to supply a complete explanation for deeper absence.", cost: "A real population is selected to absorb discovery or destruction." },
    ],
    allocations: [
      {
        id: "clinic-treatment",
        label: "Keep the clinic running",
        claimant: "Patients, families, and medical workers",
        ordinaryGood: "Heat-intensive treatment for identifiable people",
        wake: "Power demand, movement, pharmaceutical waste, and thermal release",
        denialCost: "Patients die before the Overhead classification can be resolved.",
      },
      {
        id: "shroud-capacity",
        label: "Deepen Hush",
        claimant: "Wakekeepers and residents protected statistically by continued absence",
        ordinaryGood: "Collective concealment",
        wake: "The allocation consumes stored capacity while suppressing other activity.",
        denialCost: "The observer may identify the site as inhabited and transfer that fact beyond the tomb.",
      },
    ],
  },
  alarm: {
    originalThreat: "A verified external actor once destroyed inhabited sites after detecting their technological wake.",
    auditProblem: "The test that could establish whether the threat remains active would itself reveal the tomb.",
    currentPhase: "shadow",
    phases: [
      { phase: "shadow", description: "Sensors detect a possible observer or unexplained wake.", protection: "The tomb begins classification before committing to disruptive measures.", internalCost: "Ambiguity gives custodians reason to monitor and delay ordinary activity." },
      { phase: "hush", description: "Nonessential activity is suspended and the signature budget contracts.", protection: "The exterior profile becomes quieter while evidence is gathered.", internalCost: "Medicine, light, movement, art, and work are interrupted." },
      { phase: "fold", description: "Vulnerable populations and functions move behind deeper barriers.", protection: "Surface discovery need not reveal the whole tomb.", internalCost: "People can be trapped in sacrificial districts or separated from dependent systems." },
      { phase: "black", description: "Routes, surfaces, relays, and archives capable of linking layers are shut down.", protection: "A captured layer cannot easily expose the rest.", internalCost: "Ecologies and communities requiring continuous circulation can fail." },
      { phase: "cut", description: "Systems, routes, memories, or populations judged capable of transmitting the tomb are severed.", protection: "The protected map becomes smaller and harder to reconstruct.", internalCost: "Families, evidence, history, and inhabited districts can be erased." },
      { phase: "wake", description: "Activity resumes after the event and emergency restrictions are reviewed.", protection: "The tomb restores ordinary life without immediately repeating the same wake.", internalCost: "The authority declaring Wake can make temporary restrictions permanent." },
    ],
  },
  consequences: [
    {
      id: "clinic-visibility",
      label: "The clinic receives an explicit visibility claim",
      kind: "visibility",
      description: "Medical survival becomes a named allocation rather than an invisible exception to the signature model.",
      inheritedBy: "Patients, Wakekeepers, and every district competing for detectable capacity",
    },
    {
      id: "seventh-route",
      label: "The omitted route becomes transferable evidence",
      kind: "route",
      description: "A pressure-coded path to the sealed neighborhood can now be copied, audited, exploited, or constitutionally protected.",
      inheritedBy: "The sealed neighborhood, smugglers, custodians, and outside actors who acquire the map",
    },
    {
      id: "alarm-evidence",
      label: "The Alarm acquires a public contamination history",
      kind: "archive",
      description: "The threat record survives with the interventions that made it visible and the limits that prevent certainty.",
      inheritedBy: "The Witness House, Seal Court, and future Opening Councils",
    },
    {
      id: "changed-jurisdiction",
      label: "The hub inherits another sovereign claimant",
      kind: "jurisdiction",
      description: "The previously omitted district enters politics without surrendering every route, identity, and refusal to one complete map.",
      inheritedBy: "Both neighborhoods, the Buried Commons Guild, and whoever next approaches the grave skin",
    },
  ],
  storyPhysics: {
    noPerfectInvisibility: true,
    everyComfortHasWake: true,
    everyLayerHasResidue: true,
    mapIsPoliticalClaim: true,
    defensesOutliveEnemies: true,
    externalOpacityCanCrownWithin: true,
    hubIsStory: true,
    everyDelveChangesTomb: true,
    treasureCreatesConstituencies: true,
    scaleIsDistributed: true,
  },
  delves: [
    {
      id: "keep-the-clinic-lit",
      name: "Keep the Clinic Lit",
      description: "Protect an ordinary good while the first Shadow order turns identifiable patients into contested wake.",
      tierId: "ordinary-life",
      layer: "common-depths",
      depth: { signal: 2, administrative: 2, interpretive: 1 },
      expedition: {
        objective: "Keep the heat-intensive treatment operating through the first Alarm review.",
        authorizedRoute: "The clinic, district heat exchange, and Wakekeeper allocation chamber",
        signatureBudget: "One treatment cycle before the stored thermal margin is exhausted",
        authority: "A provisional order jointly issued by the clinic and district assembly",
        claimToProve: "The clinic's wake can be masked without forcing a full Hush.",
        inheritance: "A public rule determining whether identifiable medical need can override statistical concealment.",
      },
      difficulty: 12,
      minAgents: 3,
      maxAgents: 7,
      requiredRoles: [{ roleId: "maintainer", count: 1 }, { roleId: "surface-bearer", count: 1 }],
      checks: [
        { id: "hold-the-treatment", name: "Hold the treatment", description: "Keep patients alive without hiding the cost inside an abstract population model.", scope: "role", roleIds: ["maintainer", "surface-bearer"], weights: { care: 0.5, systems: 0.35, resolve: 0.15 }, threshold: 5 },
        { id: "spend-the-wake", name: "Spend the wake", description: "Allocate heat and movement while preserving a credible exterior classification.", scope: "team", weights: { opacity: 0.45, jurisdiction: 0.25, systems: 0.3 }, threshold: 4 },
      ],
      success: "The treatment completes and the visibility claim enters the public ledger instead of disappearing into emergency discretion.",
      partial: "Most patients survive, but the district spends capacity another layer expected to receive.",
      failure: "Hush closes the clinic. The deaths become the first named cost of preserving the Alarm.",
      reputationGain: 2,
      currencyReward: 20,
      consequenceId: "clinic-visibility",
    },
    {
      id: "follow-the-seventh-route",
      name: "Follow the Seventh Route",
      description: "Descend through the quiet works and a route every official map calls collapsed.",
      tierId: "descent",
      layer: "quiet-works",
      depth: { material: 3, administrative: 4, historical: 4, interpretive: 3 },
      accessAfter: "keep-the-clinic-lit",
      expedition: {
        objective: "Reach the source of the pressure code and determine whether an omitted population is using the route.",
        authorizedRoute: "A maintenance bypass not recognized by the public domestic map",
        signatureBudget: "No open relay and one temporary atmosphere bridge",
        authority: "The Buried Commons Guild under a contested Witness House warrant",
        claimToProve: "The transit ring is inhabited rather than merely producing legacy mechanical noise.",
        inheritance: "A copied route, a newly targetable population, and a jurisdiction claim against the old Cut.",
      },
      difficulty: 20,
      minAgents: 4,
      maxAgents: 7,
      requiredRoles: [{ roleId: "maintainer", count: 1 }, { roleId: "interlocutor", count: 1 }, { roleId: "witness", count: 1 }],
      checks: [
        { id: "read-the-works", name: "Read the works", description: "Distinguish living maintenance from the residue of abandoned machinery.", scope: "role", roleIds: ["maintainer", "witness"], weights: { systems: 0.45, evidence: 0.35, opacity: 0.2 }, threshold: 6 },
        { id: "cross-the-dead-map", name: "Cross the dead map", description: "Use a route without accepting the official history that makes its inhabitants impossible.", scope: "team", weights: { jurisdiction: 0.4, evidence: 0.25, resolve: 0.2, care: 0.15 }, threshold: 5 },
      ],
      success: "The seventh route reaches homes and a school. The official collapse becomes evidence of an inhabited Cut.",
      partial: "The population is proven, but the atmosphere bridge exposes enough traffic to make the route easier to trace.",
      failure: "The old transit system treats the party as enemy traffic and seals the route around the evidence.",
      reputationGain: 3,
      currencyReward: 30,
      consequenceId: "seventh-route",
    },
    {
      id: "classify-overhead",
      name: "Classify Overhead",
      description: "Bring the observer, the tomb's neglected wake, and the original Alarm record into one contested evidentiary venue.",
      tierId: "breach",
      layer: "custodial-ring",
      depth: { signal: 5, administrative: 5, historical: 4, interpretive: 5 },
      accessAfter: "follow-the-seventh-route",
      expedition: {
        objective: "Determine what the anomaly can support before Hush advances to Black and Cut.",
        authorizedRoute: "The Seal Court sensor archive and first-witness comparison chamber",
        signatureBudget: "One active observation window whose use becomes detectable",
        authority: "A divided Seal Court under public district observation",
        claimToProve: "The anomaly is external attention, internal failure, or a combination whose causes must remain distinct.",
        inheritance: "A qualified threat record and a legitimacy judgment concerning the current Alarm authority.",
      },
      difficulty: 28,
      minAgents: 5,
      maxAgents: 7,
      requiredRoles: [{ roleId: "wakekeeper", count: 1 }, { roleId: "witness", count: 1 }, { roleId: "deliberator", count: 1 }],
      checks: [
        { id: "preserve-provenance", name: "Preserve provenance", description: "Attach every intervention and limit to the claim before factions convert it into certainty.", scope: "role", roleIds: ["witness", "deliberator"], weights: { evidence: 0.55, jurisdiction: 0.2, opacity: 0.15, resolve: 0.1 }, threshold: 7 },
        { id: "hold-asymmetric-risk", name: "Hold asymmetric risk", description: "Act before the observer's intention and the tomb's own failure can be completely separated.", scope: "team", weights: { resolve: 0.35, opacity: 0.25, care: 0.2, systems: 0.2 }, threshold: 6 },
      ],
      success: "The evidence remains contested but usable. No institution can promote quiet or opening into unqualified certainty.",
      partial: "The observer is real, but its purpose remains unresolved and one faction captures the most legible receipt.",
      failure: "The observation window is treated as proof of the conclusion it was built to test, contaminating both the threat record and the shroud.",
      reputationGain: 4,
      currencyReward: 40,
      consequenceId: "alarm-evidence",
    },
    {
      id: "return-with-another-map",
      name: "Return With Another Map",
      description: "Return to the hub with the omitted population, the qualified evidence, and a decision about who may control the next visibility claim.",
      tierId: "return",
      layer: "black-core",
      depth: { material: 4, signal: 5, administrative: 5, historical: 5, interpretive: 5 },
      accessAfter: "classify-overhead",
      expedition: {
        objective: "Prevent either total erasure or total legibility while the tomb chooses its next Alarm state.",
        authorizedRoute: "The first witness chamber and the seventh route under joint custody",
        signatureBudget: "Enough capacity for one bounded contact, closure, or counter-signal",
        authority: "A temporary Door Assembly including the omitted district and surface families",
        claimToProve: "The current tomb can preserve opacity without keeping the newly recognized population politically unreal.",
        inheritance: "A changed jurisdiction, a durable route rule, and an Alarm no longer owned by one complete map.",
      },
      difficulty: 36,
      minAgents: 6,
      maxAgents: 7,
      requiredRoles: [{ roleId: "exception", count: 1 }, { roleId: "surface-bearer", count: 1 }, { roleId: "wakekeeper", count: 1 }],
      checks: [
        { id: "recognize-without-owning", name: "Recognize without owning", description: "Give the omitted district standing without turning recognition into universal route and population data.", scope: "team", weights: { jurisdiction: 0.35, opacity: 0.3, care: 0.2, evidence: 0.15 }, threshold: 7 },
        { id: "invalidate-the-model", name: "Invalidate the model", description: "Let the sovereign exception refuse the identity and sacrifice assigned by both the old Alarm and the opening plan.", scope: "role", roleIds: ["exception"], weights: { resolve: 0.45, opacity: 0.25, jurisdiction: 0.2, care: 0.1 }, threshold: 8 },
      ],
      success: "The tomb keeps a shroud but loses the right to describe the omitted district as empty. The hub inherits another sovereign claimant.",
      partial: "Recognition survives through a narrow route while the Wakekeepers retain emergency control over contact.",
      failure: "The choice collapses into total closure or total disclosure, and one population's safety becomes another institution's proof of authority.",
      reputationGain: 5,
      currencyReward: 50,
      consequenceId: "changed-jurisdiction",
    },
  ],
  notes: {
    status: "private authoring seed",
    instruction: "Replace every local particular. Preserve the eight-pressure mechanism, evidence discipline, incompatible responsibilities, classification-changing escalation, and inherited consequence.",
  },
};
