/* Generated by the UNDERDRAIN Arc-capsule finalizer from exact Arc authority.
 * This placeholder must never enter a qualified standalone build. */
globalThis.UnderdrainArc = globalThis.UnderdrainArc || { placeholder: true };
