using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

namespace Axm.Rodoh.Action.Editor
{
    /// <summary>
    /// Binds the governed motion clips generated by ActionGovernedProductionBatch
    /// into player and enemy AnimatorControllers, then installs those controllers
    /// on the governed prefabs. Arc state remains the source of mode and position;
    /// root motion is disabled and the procedural driver remains the low-tier fallback.
    /// </summary>
    public static class ActionGovernedMotionAugmentBatch
    {
        private const string Format = "rodoh-action-governed-motion-augmentation/1";

        [Serializable]
        private sealed class Receipt
        {
            public string format = Format;
            public string status = "fail";
            public string generatedAt = DateTime.UtcNow.ToString("O");
            public string unityVersion = Application.unityVersion;
            public string manifest;
            public string manifestId;
            public string assetRoot;
            public string playerController;
            public string enemyController;
            public int motionClips;
            public int controllers;
            public int prefabsBound;
            public bool rootMotion;
            public bool proceduralFallbackRetained;
            public bool actionStateDriven;
            public string actionAuthority = "Arc replay and axm-action-receipt/1";
            public string animationAuthority = "presentation-only AXM_Mode projection";
            public string error;
        }

        private sealed class StateBinding
        {
            public string name;
            public int mode;
            public AnimationClip clip;
        }

        public static void Run()
        {
            var outputRoot = Path.GetFullPath(GetArgument("-outputRoot") ?? Path.Combine("local", "action-production", "receipts"));
            var receipt = new Receipt();
            try
            {
                var manifestPath = Path.GetFullPath(GetRequiredArgument("-manifest"));
                var requestedRoot = (GetArgument("-assetRoot") ?? string.Empty).Replace('\\', '/').TrimEnd('/');
                if (!File.Exists(manifestPath)) throw new FileNotFoundException("Governed presentation manifest is absent.", manifestPath);
                var manifest = JsonUtility.FromJson<ActionPresentationManifest>(File.ReadAllText(manifestPath));
                if (manifest == null) throw new InvalidOperationException("Governed presentation manifest did not parse.");
                var errors = manifest.Validate();
                if (errors.Count > 0) throw new InvalidOperationException("Governed presentation manifest is invalid: " + string.Join(" ", errors));
                var assetRoot = ResolveAssetRoot(manifest, requestedRoot);
                EnsureAssetFolder(assetRoot + "/Motion");

                var clips = LoadMotionSet(manifest.player.motionSet);
                var playerControllerPath = assetRoot + "/Motion/Player.controller";
                var enemyControllerPath = assetRoot + "/Motion/Enemy.controller";
                var playerController = CreateController(playerControllerPath, new[]
                {
                    State("Idle", 0, clips["idle"]),
                    State("Light", 1, clips["light"]),
                    State("Heavy", 2, clips["heavy"]),
                    State("Dodge", 3, clips["dodge"]),
                    State("Parry", 4, clips["parry"]),
                    State("Stagger", 5, clips["stagger"]),
                    State("Defeat", 6, clips["defeat"]),
                });
                var enemyController = CreateController(enemyControllerPath, new[]
                {
                    State("Approach", 0, clips["move"]),
                    State("Telegraph", 1, clips["parry"]),
                    State("Active", 2, clips["light"]),
                    State("Recover", 3, clips["idle"]),
                    State("Stagger", 4, clips["stagger"]),
                    State("Defeat", 5, clips["defeat"]),
                });

                var prefabs = 0;
                BindPrefab(manifest.player.bodyPrefab, playerController);
                prefabs += 1;
                manifest.player.animatorController = playerControllerPath;
                foreach (var enemy in manifest.enemies)
                {
                    BindPrefab(enemy.bodyPrefab, enemyController);
                    enemy.animatorController = enemyControllerPath;
                    prefabs += 1;
                }

                var governedErrors = manifest.Validate();
                if (governedErrors.Count > 0) throw new InvalidOperationException("Motion-bound presentation manifest is invalid: " + string.Join(" ", governedErrors));
                File.WriteAllText(manifestPath, JsonUtility.ToJson(manifest, true) + Environment.NewLine, new UTF8Encoding(false));
                AssetDatabase.SaveAssets();
                AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport | ImportAssetOptions.ForceUpdate);

                VerifyPrefab(manifest.player.bodyPrefab, playerControllerPath);
                foreach (var enemy in manifest.enemies) VerifyPrefab(enemy.bodyPrefab, enemyControllerPath);
                if (AssetDatabase.LoadAssetAtPath<AnimatorController>(playerControllerPath) == null) throw new InvalidOperationException("Governed player controller did not import.");
                if (AssetDatabase.LoadAssetAtPath<AnimatorController>(enemyControllerPath) == null) throw new InvalidOperationException("Governed enemy controller did not import.");

                receipt.status = "pass";
                receipt.manifest = manifestPath;
                receipt.manifestId = manifest.manifestId;
                receipt.assetRoot = assetRoot;
                receipt.playerController = playerControllerPath;
                receipt.enemyController = enemyControllerPath;
                receipt.motionClips = clips.Count;
                receipt.controllers = 2;
                receipt.prefabsBound = prefabs;
                receipt.rootMotion = false;
                receipt.proceduralFallbackRetained = true;
                receipt.actionStateDriven = true;
                Directory.CreateDirectory(outputRoot);
                var receiptPath = Path.Combine(outputRoot, "governed-motion-augmentation.json");
                File.WriteAllText(receiptPath, JsonUtility.ToJson(receipt, true) + Environment.NewLine, new UTF8Encoding(false));
                Debug.Log("RODOH governed action motion augmentation passed: " + receiptPath);
                if (Application.isBatchMode) EditorApplication.Exit(0);
            }
            catch (Exception exception)
            {
                receipt.status = "fail";
                receipt.error = exception.ToString();
                try
                {
                    Directory.CreateDirectory(outputRoot);
                    File.WriteAllText(Path.Combine(outputRoot, "governed-motion-augmentation.json"), JsonUtility.ToJson(receipt, true) + Environment.NewLine, new UTF8Encoding(false));
                }
                catch
                {
                    // Preserve the controlling augmentation failure.
                }
                Debug.LogException(exception);
                if (Application.isBatchMode) EditorApplication.Exit(1);
                else throw;
            }
        }

        private static StateBinding State(string name, int mode, AnimationClip clip)
        {
            return new StateBinding { name = name, mode = mode, clip = clip };
        }

        private static Dictionary<string, AnimationClip> LoadMotionSet(ActionMotionSet motion)
        {
            if (motion == null) throw new InvalidOperationException("Governed player motion set is absent.");
            var values = new Dictionary<string, AnimationClip>(StringComparer.Ordinal)
            {
                ["idle"] = RequireClip(motion.idle, "idle"),
                ["move"] = RequireClip(motion.move, "move"),
                ["light"] = RequireClip(motion.light, "light"),
                ["heavy"] = RequireClip(motion.heavy, "heavy"),
                ["dodge"] = RequireClip(motion.dodge, "dodge"),
                ["parry"] = RequireClip(motion.parry, "parry"),
                ["stagger"] = RequireClip(motion.stagger, "stagger"),
                ["defeat"] = RequireClip(motion.defeat, "defeat"),
            };
            return values;
        }

        private static AnimationClip RequireClip(string path, string label)
        {
            if (string.IsNullOrWhiteSpace(path)) throw new InvalidOperationException("Governed " + label + " motion path is absent.");
            var normalized = path.Replace('\\', '/');
            if (!normalized.StartsWith("Assets/", StringComparison.Ordinal)) throw new InvalidOperationException("Governed motion path escapes Assets/: " + normalized);
            var clip = AssetDatabase.LoadAssetAtPath<AnimationClip>(normalized);
            if (clip == null) throw new InvalidOperationException("Governed " + label + " motion clip did not import: " + normalized);
            return clip;
        }

        private static AnimatorController CreateController(string path, StateBinding[] bindings)
        {
            AssetDatabase.DeleteAsset(path);
            var controller = AnimatorController.CreateAnimatorControllerAtPath(path);
            if (controller == null) throw new InvalidOperationException("Unity refused to create governed AnimatorController: " + path);
            controller.AddParameter("AXM_Mode", AnimatorControllerParameterType.Int);
            controller.AddParameter("AXM_ModeTick", AnimatorControllerParameterType.Int);
            controller.AddParameter("AXM_Health", AnimatorControllerParameterType.Int);
            controller.AddParameter("AXM_Active", AnimatorControllerParameterType.Bool);
            controller.AddParameter("AXM_Hit", AnimatorControllerParameterType.Trigger);
            controller.AddParameter("AXM_Parry", AnimatorControllerParameterType.Trigger);
            controller.AddParameter("AXM_Dodge", AnimatorControllerParameterType.Trigger);
            controller.AddParameter("AXM_Defeat", AnimatorControllerParameterType.Trigger);
            controller.AddParameter("AXM_Objective", AnimatorControllerParameterType.Trigger);
            var machine = controller.layers[0].stateMachine;
            foreach (var binding in bindings)
            {
                if (binding.clip == null) throw new InvalidOperationException("Governed controller state lacks a motion clip: " + binding.name);
                var state = machine.AddState(binding.name);
                state.motion = binding.clip;
                state.writeDefaultValues = false;
                if (binding.mode == 0) machine.defaultState = state;
                var transition = machine.AddAnyStateTransition(state);
                transition.hasExitTime = false;
                transition.hasFixedDuration = true;
                transition.duration = 0.04f;
                transition.canTransitionToSelf = false;
                transition.AddCondition(AnimatorConditionMode.Equals, binding.mode, "AXM_Mode");
            }
            EditorUtility.SetDirty(controller);
            return controller;
        }

        private static void BindPrefab(string path, RuntimeAnimatorController controller)
        {
            if (string.IsNullOrWhiteSpace(path)) throw new InvalidOperationException("Governed body prefab path is absent.");
            var normalized = path.Replace('\\', '/');
            if (!normalized.StartsWith("Assets/", StringComparison.Ordinal)) throw new InvalidOperationException("Governed body path escapes Assets/: " + normalized);
            var root = PrefabUtility.LoadPrefabContents(normalized);
            if (root == null) throw new InvalidOperationException("Unity refused to open governed body prefab: " + normalized);
            try
            {
                var animator = root.GetComponent<Animator>() ?? root.AddComponent<Animator>();
                animator.runtimeAnimatorController = controller;
                animator.applyRootMotion = false;
                animator.updateMode = AnimatorUpdateMode.Normal;
                var binding = root.GetComponent<ActionActorBinding>() ?? root.AddComponent<ActionActorBinding>();
                var visual = binding.VisualRoot;
                if (visual == root.transform)
                {
                    var authored = root.transform.Find("Visual");
                    if (authored != null) visual = authored;
                }
                binding.Configure(binding.ActorId, animator, visual);
                if (PrefabUtility.SaveAsPrefabAsset(root, normalized) == null) throw new InvalidOperationException("Unity refused to save motion-bound governed prefab: " + normalized);
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(root);
            }
        }

        private static void VerifyPrefab(string path, string expectedControllerPath)
        {
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
            if (prefab == null) throw new InvalidOperationException("Governed body is absent after motion augmentation: " + path);
            var animator = prefab.GetComponent<Animator>();
            if (animator == null || animator.runtimeAnimatorController == null) throw new InvalidOperationException("Governed body lacks its state-driven Animator: " + path);
            if (AssetDatabase.GetAssetPath(animator.runtimeAnimatorController) != expectedControllerPath) throw new InvalidOperationException("Governed body names the wrong AnimatorController: " + path);
            if (animator.applyRootMotion) throw new InvalidOperationException("Governed body enabled root motion: " + path);
            var binding = prefab.GetComponent<ActionActorBinding>();
            if (binding == null || binding.VisualRoot == prefab.transform) throw new InvalidOperationException("Governed body lost its authored Visual root: " + path);
            foreach (var body in prefab.GetComponentsInChildren<Rigidbody>(true)) if (!body.isKinematic || body.detectCollisions || body.useGravity) throw new InvalidOperationException("Governed body retains active rigid-body authority: " + path);
            foreach (var collider in prefab.GetComponentsInChildren<Collider>(true)) if (collider.enabled) throw new InvalidOperationException("Governed body retains an active collider: " + path);
            foreach (var character in prefab.GetComponentsInChildren<CharacterController>(true)) if (character.enabled) throw new InvalidOperationException("Governed body retains an active CharacterController: " + path);
        }

        private static string ResolveAssetRoot(ActionPresentationManifest manifest, string requested)
        {
            if (!string.IsNullOrWhiteSpace(requested))
            {
                if (!requested.StartsWith("Assets/", StringComparison.Ordinal)) throw new InvalidOperationException("Governed asset root must remain under Assets/.");
                return requested;
            }
            if (manifest.provenance?.assetRoots != null)
            {
                for (var index = manifest.provenance.assetRoots.Length - 1; index >= 0; index -= 1)
                {
                    var root = manifest.provenance.assetRoots[index]?.Replace('\\', '/').TrimEnd('/');
                    if (!string.IsNullOrWhiteSpace(root) && root.Contains("ActionProduction", StringComparison.Ordinal)) return root;
                }
            }
            throw new InvalidOperationException("Governed asset root could not be derived from presentation provenance.");
        }

        private static void EnsureAssetFolder(string path)
        {
            Directory.CreateDirectory(Path.GetFullPath(path));
            AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
        }

        private static string GetRequiredArgument(string name)
        {
            var value = GetArgument(name);
            if (string.IsNullOrWhiteSpace(value)) throw new ArgumentException("Missing required command-line argument " + name + ".");
            return value;
        }

        private static string GetArgument(string name)
        {
            var arguments = Environment.GetCommandLineArgs();
            for (var index = 0; index < arguments.Length - 1; index += 1) if (arguments[index] == name) return arguments[index + 1];
            return null;
        }
    }
}
