import type { InfrastructureFacility } from "../engine/types.js";

// Facilities are an engine-level fixed set (the InfrastructureFacility union),
// not arc data. These human-readable strings mirror the maps BaseScreen renders;
// duplicated intentionally so the codex does not depend on a game screen.
const FACILITY_DESC: Record<InfrastructureFacility, string> = {
  Quarters: "Roster capacity (5 per level).",
  Production: "Crafts gear. Output scales with assigned agents' base efficiency.",
  Recreation: "Stress recovery. Improves recruitment pool quality.",
  Research: "Unlocks challenge intel and arc lore.",
  Training: "Accelerates stat growth for assigned agents.",
  Storage: "Resource capacity between cycles.",
  Medical: "Reduces downed-agent recovery time.",
};

// What each added level changes — the direct answer to "what does upgrading do".
const FACILITY_UPGRADE: Record<InfrastructureFacility, string> = {
  Quarters: "Each level raises the roster cap by 5, letting you carry more agents.",
  Production: "Higher level multiplies per-agent material output each cycle.",
  Recreation: "Higher level raises the morale floor (level × 10) for assigned agents.",
  Research: "Higher level increases intel generated by assigned agents.",
  Training: "Higher level grows assigned agents' attributes faster — the long-term fix for failed stat checks.",
  Storage: "Higher level protects a larger resource stockpile between cycles.",
  Medical: "Higher level shortens downed-agent recovery time.",
};

export default function FacilityRef({
  facility,
}: {
  facility: InfrastructureFacility;
}): JSX.Element | null {
  if (!facility || !FACILITY_DESC[facility]) return null;

  return (
    <div className="codex-entry">
      <div className="codex-entry-name">{facility}</div>
      <div className="codex-entry-desc">{FACILITY_DESC[facility]}</div>

      <div className="codex-meta-row">
        <strong>When you upgrade:</strong>
        <div>{FACILITY_UPGRADE[facility]}</div>
      </div>
    </div>
  );
}
