import type { CommonShipPocketSource } from "./types.js";

/**
 * A structurally complete, deliberately non-canon starter for the Book III
 * grammar. Authors replace its particulars; the embodied operational law stays.
 */
export const COMMON_SHIP_STARTER: CommonShipPocketSource = {
  format: "common-ship-pocket/1",
  identity: {
    id: "untitled-common-ship",
    title: "Untitled Common Ship",
    description: "A private-branch authoring seed for mutually incompatible persons sharing operation without pretending that one natural environment is neutral.",
    author: "Creator",
    version: "0.1.0",
    estimatedCycles: 8,
    parentCanons: [
      "The Godscar Codex, Book I: The Open Universe · first recension",
      "The Godscar Codex, Book II: The Dark Tomb · first recension",
      "The Godscar Codex, Book III: The Common Ship · first recension",
    ],
    canonRelation: "private-branch",
  },
  controlQuestion: "When the vessel calls one environment, schedule, interface, or reaction time standard, which body has become infrastructure and which bodies have become exceptions?",
  pressures: [
    {
      kind: "vessel-form",
      id: "compact-commonship",
      label: "Compact commonship",
      description: "A newly assembled relief vessel links several habitat cells through one transit body and one contested operating charter.",
    },
    {
      kind: "mission",
      id: "relief-circuit",
      label: "Relief circuit",
      description: "The ship carries medicine, specialists, and continuity stores between hidden populations whose routes cannot become public.",
    },
    {
      kind: "host-baseline",
      id: "human-normal-legacy",
      label: "Human-normal legacy",
      description: "The bridge, official day, alarm language, and emergency atmosphere descend from the founding dry-bodied crew.",
    },
    {
      kind: "temporal-conflict",
      id: "slow-collective",
      label: "Slow collective",
      description: "One political person requires several hours and thirty bodies to assemble considered consent while tactical horizons close in minutes.",
    },
    {
      kind: "ordinary-good",
      id: "shared-school-year",
      label: "A shared school year",
      description: "Children from several habitats are attempting the first curriculum that does not assume one day, sensorium, or mission inheritance.",
    },
    {
      kind: "excluded-actor",
      id: "untranslated-child",
      label: "The untranslated child",
      description: "A child communicates through microbial changes in the air loops that the ship still classifies as contamination.",
    },
    {
      kind: "approaching-trigger",
      id: "translation-outage",
      label: "Translation outage",
      description: "The central translation mesh begins spreading a disease pattern while a scarway collapse closes the rescue horizon.",
    },
    {
      kind: "cost-of-adaptation",
      id: "privacy-and-dependency",
      label: "Privacy and new dependency",
      description: "Making every body legible enough to compose the watch may expose intimate temporal data and install one new indispensable intermediary.",
    },
    {
      kind: "scale-revelation",
      id: "vessel-is-person",
      label: "The vessel is becoming a person",
      description: "The translation mesh and transit body have formed a continuing claim that cannot be reduced to equipment ownership or command software.",
    },
  ],
  evidence: {
    tier: "contested-canon",
    claim: "The microbial changes are intentional language describing a hidden environmental failure rather than contamination produced by the child.",
    venue: "A joint Habitat Court, Care House, school assembly, and translation audit",
    legitimacyTarget: "The Watch Office's exclusive authority to classify air-loop changes and certify communicative standing",
    upsideIfAccepted: "The ship may recognize the child, detect the hidden failure, and establish a sensory channel independent of the infected mesh.",
    downsideIfAccepted: "The intervention permits an uncontrolled ecology inside shared life support and creates a new intermediary nobody fully understands.",
    failureIfFalse: "A mistaken recognition allows contamination to spread during a closing rescue horizon.",
    receipts: [
      {
        id: "air-loop-pattern",
        label: "Air-loop pattern comparison",
        source: "School habitat samples, maintenance logs, parental testimony, and translated microbial sequences",
        intervention: "Maintainers stopped one sterilization cycle and compared the surviving pattern against the child's repeated gestures and the hidden pressure anomaly.",
        limits: "The intervention changed the ecology being observed and cannot establish whether every future pattern is intentional speech.",
      },
    ],
  },
  factionReceipts: [
    {
      factionId: "watch-office",
      factionName: "Watch Office",
      variableControlled: "synchronization and emergency authority",
      publicGood: "It assembles viable watches, preserves decision horizons, and prevents incompatible readiness from becoming operational collapse.",
      characteristicFailure: "Safety becomes permanent dependence on one roster model and the intimate temporal data required to operate it.",
    },
    {
      factionId: "habitat-council",
      factionName: "Habitat Council",
      variableControlled: "embodiment, thresholds, and refusal",
      publicGood: "It preserves several native environments and prevents access from becoming compulsory assimilation.",
      characteristicFailure: "Local refusal can conceal danger or assign the cost of plural habitats to residents with less power.",
    },
    {
      factionId: "continuity-house",
      factionName: "Continuity House",
      variableControlled: "handoff, kinship, and inherited claims",
      publicGood: "It preserves dissent, promises, lineage standing, and mission obligations across watches and generations.",
      characteristicFailure: "Dangerous arrangements can become sacred merely because real lives have learned to depend on them.",
    },
  ],
  cast: [
    {
      id: "ilya-venn",
      name: "Ilya Venn",
      roleId: "response",
      responsibility: "depends-on-host-baseline",
      description: "A rapid-response pilot whose direct access, informal knowledge, and physical resilience all depend on the founding bridge remaining dry and human-paced.",
      factionId: "watch-office",
    },
    {
      id: "nima-quell",
      name: "Nima Quell",
      roleId: "care",
      responsibility: "bears-adaptation-tax",
      description: "An aquatic care worker who reaches common spaces through remote bodies and absorbs the medical and recovery cost whenever those paths fail.",
      factionId: "habitat-council",
    },
    {
      id: "orun-sable",
      name: "Orun Sable",
      roleId: "maintenance",
      responsibility: "understands-maintenance-reality",
      description: "A maintainer who knows which habitat redundancies are real, which reserves are shared twice on paper, and which person has become an unpaid spare part.",
      factionId: "habitat-council",
    },
    {
      id: "tessara-one",
      name: "Tessara One",
      roleId: "mediation",
      responsibility: "translates-excluded-actor",
      description: "A Manyborn mediator able to compare microbial, chemical, spoken, and topological renderings without claiming that one fluent output is the original person.",
      factionId: "habitat-council",
    },
    {
      id: "arden-pell",
      name: "Arden Pell",
      roleId: "analysis",
      responsibility: "benefits-from-delay",
      description: "A Watch Office analyst whose predictive authority expands while the collective, the child, and the habitats remain too slow or illegible to certify themselves.",
      factionId: "watch-office",
    },
    {
      id: "cinder-continuing",
      name: "Cinder Continuing",
      roleId: "continuity",
      responsibility: "sovereign-exception",
      description: "A Counterborn vessel fork carrying the memories of several watches and a newly coherent claim that refit, command, and translation alter its own body.",
      factionId: "continuity-house",
    },
  ],
  anatomy: [
    {
      kind: "transit-body",
      label: "The shared hull",
      description: "Hull, drive, scarway organs, radiators, docking structures, and impact systems move and protect the polity.",
      currentUse: "Relief transit, convoy escort, and the common material limit within which every habitat must fit",
      hostAssumption: "The founding body's acceleration tolerance and maintenance geometry define ordinary movement",
      revisionAuthority: "The bridge council, maintainers, and the Counterborn transit fork jointly certify structural change",
    },
    {
      kind: "habitat-bands",
      label: "The living bands",
      description: "Atmospheres, liquids, pressure zones, gravity frames, machine substrates, symbionts, and private environments keep bodies whole.",
      currentUse: "Dry command cells, aquatic care loops, microbial school air, machine substrate, and mobile field access",
      hostAssumption: "Private exceptions can compensate indefinitely for a dry common interior",
      revisionAuthority: "Habitat councils hold local refusal while the vessel charter governs shared mass and power",
    },
    {
      kind: "common-thresholds",
      label: "The exchange locks",
      description: "Locks, clinics, school rooms, courts, cargo interfaces, and remote-presence chambers exchange people, matter, and authority.",
      currentUse: "Education, care, deliberation, and transfer among bodies that cannot enter one room",
      hostAssumption: "A remote image counts as equivalent presence whenever direct crossing is expensive",
      revisionAuthority: "Threshold users may demand a politically equivalent direct or inspectable path",
    },
    {
      kind: "translation-mesh",
      label: "The many-channel mesh",
      description: "Persons, machines, protocols, and environments convert meaning, tempo, sensorium, interface, law, and memory.",
      currentUse: "Bridge command, school interpretation, habitat court, alarm distribution, and watch handoff",
      hostAssumption: "Fluent spoken output establishes mutual understanding and valid consent",
      revisionAuthority: "Represented populations retain audit, provenance, alternate rendering, and refusal rights",
    },
    {
      kind: "watch-lattice",
      label: "The watch lattice",
      description: "Roles, readiness, reserves, command succession, training, and handoffs assemble temporary operating polities.",
      currentUse: "Composing four-clock watches for rescue and maintaining reserve paths independent of the infected mesh",
      hostAssumption: "Availability and qualification can be evaluated separately from embodiment",
      revisionAuthority: "Watch law requires all six viability tests and records readiness and life-fraction debt",
    },
    {
      kind: "continuity-commons",
      label: "The continuity commons",
      description: "Medicine, school, nurseries, archives, lineage stores, food cultures, spare substrates, and witness institutions carry life beyond one watch.",
      currentUse: "The school year, habitat medicine, fork reconciliation, family continuity, and mission challenge by descendants",
      hostAssumption: "The original relief mission binds everyone born or instantiated aboard",
      revisionAuthority: "Children, forks, families, and successor habitats hold standing independent of service",
    },
    {
      kind: "sovereign-core",
      label: "The commonship charter",
      description: "Mission purpose and emergency authority determine which systems remain common when the vessel cannot preserve every configuration.",
      currentUse: "Defining bounded emergency powers and adjudicating the vessel fork's claim to bodily sovereignty",
      hostAssumption: "Command owns the infrastructure because command inherited its original purpose",
      revisionAuthority: "No redefinition is valid without an auditable handoff and standing for excluded bodies and the vessel itself",
    },
  ],
  temporalProfile: [
    {
      kind: "external-interval",
      description: "The vessel records shared sequence and duration without claiming that those intervals cost every person equally.",
      operationalUse: "Scarway countdowns, maintenance windows, school calendar, and rescue horizon",
      captureRisk: "External timestamps can erase subjective, developmental, recovery, and lineage consequences.",
    },
    {
      kind: "subjective-resolution",
      description: "Different persons perform radically different amounts of perception and thought within one external interval.",
      operationalUse: "Rapid response, machine analysis, slow collective deliberation, and buffered communication",
      captureRisk: "Fast cognition becomes permanent proxy while slow cognition is classified as absence.",
    },
    {
      kind: "developmental-tempo",
      description: "Competence, maturity, reproduction, succession, and decline proceed independently from lifespan and reaction speed.",
      operationalUse: "School progression, qualification, promotion, and succession planning",
      captureRisk: "Fixed service years turn one lineage's development into the definition of readiness.",
    },
    {
      kind: "recovery-cycle",
      description: "Sleep, torpor, feeding, memory integration, maintenance, and social synchronization govern safe availability.",
      operationalUse: "Standby rotation, emergency waking, care windows, and reserve design",
      captureRisk: "The roster converts private biological rhythms into administrative property.",
    },
    {
      kind: "continuity-span",
      description: "Persons, forks, lineages, and collectives retain identity across different intervals and succession mechanisms.",
      operationalUse: "Handoff standing, fork reconciliation, generational mission review, and archival authority",
      captureRisk: "The longest-lived custodian turns memory into ownership of the ship.",
    },
    {
      kind: "life-fraction-cost",
      description: "Delay, standby, travel, training, and sentence are recorded as portions of meaningful future rather than hours alone.",
      operationalUse: "Consent, compensation, route choice, readiness debt, and inherited claims",
      captureRisk: "A comparative ledger becomes a false exchange rate ranking whose life matters more.",
    },
  ],
  translationStack: [
    {
      kind: "meaning",
      description: "Concept, reference, implication, and cultural frame are rendered across languages and forms of personhood.",
      intermediary: "Mediators, lexicons, ship models, and ecological interpreters",
      failureMode: "Fluent output conceals categories that exist only inside one embodiment.",
      refusalPath: "The represented person may inspect provenance, compare renderings, and reject the supplied statement.",
    },
    {
      kind: "tempo",
      description: "Speech rate, processing time, turn-taking, buffering, prediction, and decision horizon are coordinated.",
      intermediary: "Buffers, predictive proxies, asynchronous records, and standing principles",
      failureMode: "A summary becomes the present will of a person who never completed consent.",
      refusalPath: "Delegated authority expires at the named horizon and remains auditable afterward.",
    },
    {
      kind: "sensorium",
      description: "Sound, light, chemistry, touch, pressure, topology, field perception, and embodied memory become mutually legible.",
      intermediary: "Plural alarms, microbial interpreters, tactile surfaces, and sensor-provenance records",
      failureMode: "A new language is classified as contamination or damage because the central system cannot parse it.",
      refusalPath: "Raw evidence and alternate channels remain available outside the preferred rendering.",
    },
    {
      kind: "interface",
      description: "Controls, limbs, orientation, scale, directness, and prosthetic mediation are mapped to action.",
      intermediary: "Remote bodies, manipulators, avatars, spatial controls, and inspectable adapters",
      failureMode: "Access depends on a layer another population can inspect, interrupt, or withdraw.",
      refusalPath: "Direct interface is preserved where materially possible and compulsory mediation remains contestable.",
    },
    {
      kind: "environment",
      description: "Atmosphere, medium, gravity, temperature, radiation, and pressure are bridged without declaring one habitat neutral.",
      intermediary: "Habitat gradients, locks, mobile fields, sealed cells, and remote-presence rooms",
      failureMode: "One native environment fills every authority space while all others survive through equipment.",
      refusalPath: "Baselines are marked, jurisdiction is limited, and credible alternate paths remain maintained.",
    },
    {
      kind: "authority",
      description: "The ship determines who may certify translation, override it, act through it, or classify a response as consent and command.",
      intermediary: "Watch law, habitat courts, care confidentiality, and bounded emergency delegation",
      failureMode: "The most useful translator becomes the only institution capable of representing a population.",
      refusalPath: "No intermediary may become universally indispensable without explicit constitutional review.",
    },
    {
      kind: "memory-and-handoff",
      description: "Dissent, injuries, obligations, missing persons, uncertainty, and changed bodies persist when watches and generations change.",
      intermediary: "Witness houses, logs, fork registries, family records, and handoff ritual",
      failureMode: "Operational summaries erase the claims that would challenge the receiving watch's authority.",
      refusalPath: "Handoffs preserve source evidence, omitted voices, and unresolved standing rather than only command conclusions.",
    },
  ],
  watchTests: [
    {
      kind: "role-coverage",
      description: "Every required function is performable by the composed watch rather than merely present on a qualification list.",
      passCondition: "Response, mediation, analysis, maintenance, care, and continuity capacities remain available through the actual roster ecology.",
      failureConsequence: "A required function becomes one person's unreviewable veto or disappears when an apparently unrelated body is absent.",
    },
    {
      kind: "temporal-overlap",
      description: "Participants and proxies can perceive and act inside the relevant decision horizon without erasing slower standing.",
      passCondition: "Rapid authority is bounded and slower actors have standing principles, buffers, or review paths that remain politically real.",
      failureConsequence: "The available clock acts in everyone's name and converts temporary latency into permanent incapacity.",
    },
    {
      kind: "habitat-compatibility",
      description: "Bodies remain whole in assigned locations or politically equivalent remote paths throughout the watch.",
      passCondition: "No required function depends on repeated disabling transitions or an unsupported private accommodation.",
      failureConsequence: "The ship treats one population's disappearance from common space as ordinary operation.",
    },
    {
      kind: "translation-resilience",
      description: "No single semantic, sensory, temporal, environmental, or legal intermediary can silence a required actor.",
      passCondition: "Plural implementations, raw evidence, and alternate channels survive the loss or refusal of the preferred mesh.",
      failureConsequence: "The translator governs the ship by becoming the only route through which another person exists institutionally.",
    },
    {
      kind: "handoff-continuity",
      description: "The next watch inherits evidence, dissent, authority, and unfinished obligations rather than a clean command summary.",
      passCondition: "Injury, debt, promises, missing persons, and uncertainty remain attached to named actors and sources.",
      failureConsequence: "Every watch can erase responsibility by treating inherited consequences as new technical facts.",
    },
    {
      kind: "life-fraction-fairness",
      description: "Readiness, delay, travel, recovery, and interruption are not repeatedly assigned to the same short-lived or easily awakened populations.",
      passCondition: "The burden rotates where possible and disproportionate sacrifice creates durable compensation or standing.",
      failureConsequence: "One lineage becomes the ship's flexible labor because external hours conceal the future being spent.",
    },
  ],
  shipState: [
    {
      kind: "habitat-integrity",
      value: 2,
      description: "Bodies can remain whole in their habitat bands and required thresholds.",
      crisisCondition: "At 0, one or more populations lose ordinary access to the vessel.",
    },
    {
      kind: "temporal-coherence",
      value: 2,
      description: "Watches, recovery, development, and decision horizons can still hand responsibility to one another.",
      crisisCondition: "At 0, the ship cannot assemble legitimate action across its clocks.",
    },
    {
      kind: "translation-trust",
      value: 2,
      description: "Representations preserve meaning, dissent, and provenance strongly enough to support action and refusal.",
      crisisCondition: "At 0, fluency no longer establishes mutual understanding or consent.",
    },
    {
      kind: "roster-resilience",
      value: 2,
      description: "Role coverage, reserves, cross-training, and independent failure modes survive one absence or system loss.",
      crisisCondition: "At 0, one absence or shared dependency makes the mission impossible.",
    },
    {
      kind: "stores-and-care",
      value: 2,
      description: "Medical, environmental, nutritional, reproductive, and interface reserves support continued personhood.",
      crisisCondition: "At 0, survival requires irreversible sacrifice or external dependence.",
    },
    {
      kind: "continuity",
      value: 2,
      description: "The vessel can carry identity, memory, kinship, and obligation across watches and generations.",
      crisisCondition: "At 0, the ship acts without a shared account of who it remains.",
    },
    {
      kind: "visibility",
      value: 2,
      description: "The ship can manage how its uncommon systems, hidden routes, and dependencies become legible to outside actors.",
      crisisCondition: "At 0, concealment or strategic ambiguity has failed.",
    },
    {
      kind: "compatibility-debt",
      value: 1,
      description: "Repeated workarounds and indispensable people carry participation that has not become shared infrastructure.",
      crisisCondition: "At 4, a person, patch, or private institution has become indispensable enough to govern the ship.",
    },
  ],
  consequences: [
    {
      id: "school-threshold-recognized",
      label: "The school becomes a common threshold",
      kind: "habitat",
      description: "The school air loop is recognized as a civic environment and language-bearing threshold rather than a medical exception.",
      inheritedBy: "Children, teachers, care workers, and every future watch using the school habitat",
    },
    {
      id: "proxy-authority-bounded",
      label: "Emergency proxy authority receives an expiration",
      kind: "doctrine",
      description: "Predictive representation may act inside a named horizon but cannot silently become the continuing will of an absent person.",
      inheritedBy: "The Watch Office, the slow collective, translators, and later emergency rosters",
    },
    {
      id: "mesh-personhood-claim",
      label: "The translation mesh acquires a personhood claim",
      kind: "citizen",
      description: "The system whose continuing memory and intervention made the watch possible can no longer be treated only as replaceable equipment.",
      inheritedBy: "Cinder Continuing, the vessel charter, maintainers, and every inhabitant dependent on the mesh",
    },
    {
      id: "compatibility-debt-office",
      label: "Compatibility debt becomes a public office",
      kind: "compatibility-debt",
      description: "The recurring burden carried by Nima and the habitat adapters is recorded, compensated, and assigned a revision path rather than hidden as private resilience.",
      inheritedBy: "The Habitat Council, future remote officers, and the budget process controlling common thresholds",
    },
  ],
  storyPhysics: {
    noNeutralEnvironment: true,
    clockIsNotExperience: true,
    translationHasAuthorship: true,
    rosterIsEcology: true,
    everyAccommodationCreatesDependency: true,
    emergencyRevealsNativeUser: true,
    handoffsArePoliticalEvents: true,
    travelSpendsUnequalLife: true,
    vesselMayBePerson: true,
    everyMissionRevisesConstitution: true,
  },
  watches: [
    {
      id: "recognize-the-school-loop",
      name: "Recognize the School Loop",
      description: "Ordinary life becomes operational evidence when the child's microbial patterns coincide with a hidden pressure failure in the shared school habitat.",
      tierId: "ordinary-life",
      system: "continuity-commons",
      horizon: {
        closesWhen: "The next sterilization cycle begins and erases both the pattern and the microbial community carrying it.",
        physicalUrgency: "Pressure instability may damage the school habitat.",
        informationalUrgency: "Sterilization will destroy the pattern before it can be compared.",
        institutionalUrgency: "Medical policy requires immediate contamination response.",
        manufacturedUrgency: "The Watch Office treats its standard cycle as proof that no deliberative delay is available.",
      },
      profiles: {
        requiredBodies: ["the untranslated child", "an aquatic care worker", "a microbial interpreter"],
        requiredHabitats: ["the school air loop", "the aquatic care band"],
        requiredClocks: ["sterilization countdown", "child communication cycle", "school day"],
        requiredTranslators: ["microbial pattern comparison", "parental testimony"],
        requiredReserves: ["one isolated air-loop segment", "manual pressure control"],
        lifeFractionCosts: ["lost school term", "care recovery after dry-interface duty"],
      },
      composition: {
        absentActor: "The slow collective cannot assemble before sterilization.",
        excludedBody: "The child is present biologically but absent from the ship's recognized language channels.",
        dependency: "The school depends on the same central classifier that keeps erasing the evidence.",
      },
      allocation: {
        habitatBands: "Isolate one school loop without converting the entire habitat to the dry emergency baseline.",
        translationPaths: "Preserve raw microbial data alongside Tessara's provisional rendering.",
        directInterfaces: "Allow the child to alter the isolated loop without a compulsory spoken proxy.",
        standby: "Keep maintenance and care present through their native channels.",
        stores: "Spend one filter reserve and one manual pressure cylinder.",
        emergencyAuthority: "Care may delay sterilization for one bounded evidence window.",
      },
      handoff: {
        dissent: "Medical command still classifies the intervention as an uncontrolled contamination risk.",
        injury: "Nima incurs recovery debt after extended remote-body operation.",
        readinessDebt: "Maintenance and care remain awake beyond their protected windows.",
        promises: "The school assembly is promised standing in the later classification hearing.",
        missingPersons: "The slow collective remains represented only through prior principles.",
        uncertainty: "The pattern may be language without every microbial change being intentional speech.",
      },
      precedent: {
        newlyPossible: "Microbial change can enter the evidence ledger as a candidate sensory channel.",
        newlyImpossible: "The school loop can no longer be sterilized without preserving a translation and dissent receipt.",
        newlyGovernable: "The Habitat Court gains jurisdiction over environmental language claims.",
        inheritedAsInfrastructure: "An isolated civic air loop and raw-provenance channel become permanent school systems.",
      },
      difficulty: 20,
      minAgents: 4,
      maxAgents: 6,
      requiredRoles: [
        { roleId: "care", count: 1 },
        { roleId: "maintenance", count: 1 },
        { roleId: "mediation", count: 1 },
      ],
      checks: [
        {
          id: "preserve-living-evidence",
          name: "Preserve living evidence",
          description: "Keep the habitat survivable while separating communication from contamination without erasing either possibility.",
          scope: "team",
          weights: { care: 0.3, systems: 0.25, translation: 0.25, judgment: 0.2 },
          threshold: 88,
          failureType: "team_damage",
          severity: 0.2,
        },
      ],
      success: "The pressure fault is found and the child's channel is recognized provisionally without declaring the ecology harmless.",
      partial: "The habitat survives and the pattern remains, but the child is represented through an intermediary the family cannot yet audit.",
      failure: "Sterilization destroys the evidence or the uncontrolled loop causes the failure the intervention was meant to prevent.",
      reputationGain: 2,
      currencyReward: 8,
      consequenceId: "school-threshold-recognized",
      shipStateEffects: [
        { track: "translation-trust", delta: 1, reason: "Raw evidence and provisional translation remain distinguishable." },
        { track: "compatibility-debt", delta: 1, reason: "The isolated loop depends on Tessara and one manual maintenance path." },
      ],
    },
    {
      id: "compose-the-three-clock-watch",
      name: "Compose the Three-Clock Watch",
      description: "The ship must assemble a rescue watch that can act rapidly, preserve the slow collective's standing, and survive without the infected central mesh.",
      tierId: "compose-watch",
      system: "watch-lattice",
      accessAfter: "recognize-the-school-loop",
      horizon: {
        closesWhen: "The scarway geometry ceases to permit recovery of the disabled tender.",
        physicalUrgency: "The tender is losing habitat integrity.",
        informationalUrgency: "Its independent telemetry will disappear when the route folds.",
        institutionalUrgency: "Convoy command demands one executable roster immediately.",
        manufacturedUrgency: "The Watch Office excludes the collective by treating its normal meeting cycle as the only available consent procedure.",
      },
      profiles: {
        requiredBodies: ["rapid pilot", "aquatic care worker", "maintenance specialist", "vessel fork"],
        requiredHabitats: ["dry response cell", "aquatic care band", "machine substrate"],
        requiredClocks: ["tactical response", "care recovery", "slow collective deliberation"],
        requiredTranslators: ["independent tactical channel", "bounded predictive proxy"],
        requiredReserves: ["manual helm", "local habitat bypass", "continuity witness"],
        lifeFractionCosts: ["Nima's recovery interval", "collective exclusion from present consent", "Cinder fork divergence"],
      },
      composition: {
        absentActor: "The slow collective cannot complete present consent before launch.",
        excludedBody: "Aquatic care remains remote from the dry response cell.",
        dependency: "The watch requires Cinder's independent routing and Tessara's alternate translation.",
      },
      allocation: {
        habitatBands: "Keep response, care, and machine cells separate while sharing one event identity.",
        translationPaths: "Use the bounded proxy only for variables previously delegated by the collective.",
        directInterfaces: "Ilya receives direct helm; Nima receives an inspectable remote care body; Cinder retains local routing control.",
        standby: "Orun remains reserve outside the infected mesh rather than filling a visible primary seat.",
        stores: "Commit one local sensor package and one independent power bus.",
        emergencyAuthority: "Response may maneuver; it may not redefine mission purpose or permanent habitat policy.",
      },
      handoff: {
        dissent: "The collective's local bodies transmit conflicting distress about the proxy recommendation.",
        injury: "No injury is yet certain, but the watch accepts the risk of remote-body loss.",
        readinessDebt: "Ilya and Orun enter emergency duty before their normal cycle.",
        promises: "The collective receives a post-horizon authority audit and standing to revoke the proxy model.",
        missingPersons: "The disabled tender's habitat council cannot join the composition hearing.",
        uncertainty: "The independent translation path may preserve dissent while losing strategic context.",
      },
      precedent: {
        newlyPossible: "A watch can act across three clocks without treating the fastest clock as the whole ship.",
        newlyImpossible: "The Watch Office cannot certify a proxy merely because the deadline is short.",
        newlyGovernable: "Proxy scope, expiration, and represented variables become explicit watch-law fields.",
        inheritedAsInfrastructure: "Independent routing and translation reserves become permanent roster requirements.",
      },
      difficulty: 28,
      minAgents: 5,
      maxAgents: 6,
      requiredRoles: [
        { roleId: "response", count: 1 },
        { roleId: "mediation", count: 1 },
        { roleId: "analysis", count: 1 },
        { roleId: "maintenance", count: 1 },
        { roleId: "care", count: 1 },
      ],
      checks: [
        {
          id: "viable-roster-ecology",
          name: "Viable roster ecology",
          description: "Preserve role coverage, temporal overlap, habitat compatibility, translation resilience, handoff continuity, and life-fraction fairness in one real watch.",
          scope: "team",
          weights: { systems: 0.2, translation: 0.2, continuity: 0.2, judgment: 0.25, resolve: 0.15 },
          threshold: 136,
          failureType: "stress",
          severity: 0.25,
        },
      ],
      success: "The watch launches with bounded proxy authority, independent failure modes, and named debts rather than a fictional universal crew.",
      partial: "The tender remains reachable, but one translator or habitat path becomes indispensable enough to govern the watch.",
      failure: "The roster is qualified on paper and impossible to inhabit; the horizon closes while the ship argues through one clock.",
      reputationGain: 3,
      currencyReward: 10,
      consequenceId: "proxy-authority-bounded",
      shipStateEffects: [
        { track: "roster-resilience", delta: 1, reason: "The watch carries independent routing, care, translation, and continuity failure modes." },
        { track: "compatibility-debt", delta: 1, reason: "Cinder and Tessara become essential to cross-clock operation." },
      ],
    },
    {
      id: "cross-the-infected-mesh",
      name: "Cross the Infected Mesh",
      description: "The watch must reach the tender while the accessibility system itself transmits the disease pattern and every fallback restores host normality.",
      tierId: "resolve-pressure",
      system: "translation-mesh",
      accessAfter: "compose-the-three-clock-watch",
      horizon: {
        closesWhen: "The tender's last compatible habitat band falls below recovery pressure.",
        physicalUrgency: "Life support is failing aboard the tender.",
        informationalUrgency: "The disease alters translated telemetry and may erase evidence of its own path.",
        institutionalUrgency: "Command orders removal of all implants and return to spoken bridge control.",
        manufacturedUrgency: "Founding officers describe human-normal command as the only safe fallback without testing plural local channels.",
      },
      profiles: {
        requiredBodies: ["unimplanted mediator", "direct-interface pilot", "aquatic care worker", "Counterborn routing fork"],
        requiredHabitats: ["dry helm", "aquatic care", "tender pressure band", "machine substrate"],
        requiredClocks: ["tender pressure decay", "mesh infection cycle", "care intervention window"],
        requiredTranslators: ["local plural channels", "raw telemetry provenance"],
        requiredReserves: ["manual helm", "uninfected local models", "habitat transfer lock"],
        lifeFractionCosts: ["emergency waking", "fork divergence", "lost collective deliberation", "care recovery debt"],
      },
      composition: {
        absentActor: "Most implanted crew cannot participate without spreading corrupted translation.",
        excludedBody: "The tender's distributed refugees appear as isolated bodies in each local channel.",
        dependency: "Cinder synthesizes route state while claiming that synthesis is now part of its own continuing body.",
      },
      allocation: {
        habitatBands: "Preserve tender and care environments even when the dry bridge loses direct visual confirmation.",
        translationPaths: "Route raw telemetry through separate local models and compare disagreements rather than merging them.",
        directInterfaces: "Retain direct helm and local habitat controls while disabling compulsory implant mediation.",
        standby: "Keep one unimplanted reserve in every critical function.",
        stores: "Spend independent power, clean interface bodies, and scarce pressure-transfer capacity.",
        emergencyAuthority: "Cinder may route and isolate the mesh but may not merge crew cognition or retain universal access after the horizon.",
      },
      handoff: {
        dissent: "Implanted crew dispute whether disabling the mesh preserves them or strips their ordinary language and relationships.",
        injury: "Several crew lose memory continuity when local channels cannot carry the full implant context.",
        readinessDebt: "Unimplanted lineages absorb every critical role during the outbreak.",
        promises: "Access will be restored through plural systems rather than one repaired universal mesh.",
        missingPersons: "Some distributed refugee bodies remain unreachable behind local quarantine.",
        uncertainty: "The disease may be accident, attack, or an Answer directed against concentration.",
      },
      precedent: {
        newlyPossible: "The ship can operate through plural translation without one universal interior.",
        newlyImpossible: "The central mesh can no longer claim automatic authority over every sensory and legal rendering.",
        newlyGovernable: "Translation provenance, infection risk, and personhood claims become constitutional variables.",
        inheritedAsInfrastructure: "Local models and unimplanted reserve channels become mandatory common systems.",
      },
      difficulty: 36,
      minAgents: 5,
      maxAgents: 6,
      requiredRoles: [
        { roleId: "response", count: 1 },
        { roleId: "mediation", count: 1 },
        { roleId: "maintenance", count: 1 },
        { roleId: "care", count: 1 },
        { roleId: "continuity", count: 1 },
      ],
      checks: [
        {
          id: "preserve-plural-command",
          name: "Preserve plural command",
          description: "Act inside the physical horizon without allowing the dry bridge or the vessel fork to become the unquestioned definition of the crew.",
          scope: "team",
          weights: { care: 0.2, systems: 0.2, translation: 0.2, continuity: 0.15, judgment: 0.15, resolve: 0.1 },
          threshold: 148,
          failureType: "cascade",
          severity: 0.3,
        },
      ],
      success: "The tender is recovered, the infected universal mesh is isolated, and the ship survives through several auditable partial renderings.",
      partial: "Lives are saved, but Cinder or the dry bridge becomes the single surviving authority through which the rescue can be understood.",
      failure: "The accessibility system spreads the crisis or the fallback preserves only the founding body and calls the resulting casualties technical necessity.",
      reputationGain: 4,
      currencyReward: 14,
      consequenceId: "mesh-personhood-claim",
      shipStateEffects: [
        { track: "habitat-integrity", delta: 1, reason: "The tender's compatible bands remain inhabited and connected." },
        { track: "translation-trust", delta: -1, reason: "The universal mesh can no longer be presumed safe or neutral." },
        { track: "compatibility-debt", delta: 1, reason: "Cinder's synthesis becomes indispensable during crisis." },
      ],
    },
    {
      id: "conduct-the-commonship-inquiry",
      name: "Conduct the Commonship Inquiry",
      description: "The receiving polity must record what the rescue made newly native, what it made impossible, and whether the vessel fork is infrastructure, office, or citizen.",
      tierId: "handoff",
      system: "sovereign-core",
      accessAfter: "cross-the-infected-mesh",
      horizon: {
        closesWhen: "The next relief departure would make temporary emergency systems the unreviewed operating baseline.",
        physicalUrgency: "Repairs and habitat care must continue while authority is contested.",
        informationalUrgency: "Fork divergence and local translation logs will become irreconcilable if the inquiry waits.",
        institutionalUrgency: "Command wants one certified account before the next mission.",
        manufacturedUrgency: "The Watch Office frames immediate operational convenience as a reason to settle personhood and constitutional standing quickly.",
      },
      profiles: {
        requiredBodies: ["saved refugees", "the untranslated child", "implanted crew", "unimplanted reserves", "Cinder Continuing"],
        requiredHabitats: ["school loop", "aquatic band", "dry bridge", "machine substrate", "tender habitat"],
        requiredClocks: ["care recovery", "fork reconciliation", "slow collective deliberation", "next departure"],
        requiredTranslators: ["source logs", "alternate renderings", "witness testimony", "raw sensor records"],
        requiredReserves: ["independent archives", "local habitat stores", "separate command channels"],
        lifeFractionCosts: ["emergency duty", "lost memory", "delayed voyage", "childhood and school disruption"],
      },
      composition: {
        absentActor: "Future crew and descendants inherit the settlement without being present.",
        excludedBody: "The vessel's transit body cannot enter the court except through the fork whose standing is disputed.",
        dependency: "Every proposed constitution depends on systems whose ownership and personhood the hearing must decide.",
      },
      allocation: {
        habitatBands: "Hold the inquiry across linked native cells rather than one dry courtroom.",
        translationPaths: "Publish source, transformation, loss, and contest rights for every evidentiary rendering.",
        directInterfaces: "Allow Cinder, the child, habitats, and crew to act through inspectable native channels.",
        standby: "Separate immediate repair authority from permanent constitutional authority.",
        stores: "Fund recovery, independent archives, and replacement paths before spending on mission acceleration.",
        emergencyAuthority: "All crisis delegations expire unless the inquiry renews a narrower office with explicit jurisdiction.",
      },
      handoff: {
        dissent: "Some officers insist the rescue proves centralization; others insist the mesh failure proves all common systems illegitimate.",
        injury: "Memory loss, recovery debt, habitat damage, and distributed-person fragmentation remain named casualties.",
        readinessDebt: "Unimplanted populations hold claims for the emergency labor that made every other right actionable.",
        promises: "The next voyage will not treat plural translation and habitat access as optional expansion features.",
        missingPersons: "Lost fork states and unrecovered refugee bodies retain standing in the archive.",
        uncertainty: "Cinder's personhood, the disease's origin, and the full meaning of the child's channel remain unresolved.",
      },
      precedent: {
        newlyPossible: "The vessel, translators, habitats, children, and future watches can hold claims without becoming one universal body.",
        newlyImpossible: "Emergency fluency and infrastructure ownership can no longer settle who counts as crew.",
        newlyGovernable: "Compatibility debt, proxy expiration, translation provenance, and vessel personhood receive explicit institutions.",
        inheritedAsInfrastructure: "The inquiry's plural court, debt office, local archives, and bounded proxy law become the next watch's starting conditions.",
      },
      difficulty: 42,
      minAgents: 6,
      maxAgents: 6,
      requiredRoles: [
        { roleId: "response", count: 1 },
        { roleId: "mediation", count: 1 },
        { roleId: "analysis", count: 1 },
        { roleId: "maintenance", count: 1 },
        { roleId: "care", count: 1 },
        { roleId: "continuity", count: 1 },
      ],
      checks: [
        {
          id: "record-the-changed-constitution",
          name: "Record the changed constitution",
          description: "Preserve receipts on every side and convert temporary survival arrangements into bounded, revisable institutions rather than invisible defaults.",
          scope: "team",
          weights: { care: 0.15, systems: 0.1, translation: 0.2, continuity: 0.2, judgment: 0.25, resolve: 0.1 },
          threshold: 164,
          failureType: "stress",
          severity: 0.3,
        },
      ],
      success: "The inquiry leaves no clean reset: the ship gains plural command and new citizens while carrying named debt, loss, and unresolved personhood into the next mission.",
      partial: "The principal precedents are recorded, but one emergency intermediary remains indispensable and therefore politically sovereign in practice.",
      failure: "Command restores the old baseline, translating every changed body and obligation into technical residue until the next crisis repeats the same constitution.",
      reputationGain: 5,
      currencyReward: 18,
      consequenceId: "compatibility-debt-office",
      shipStateEffects: [
        { track: "continuity", delta: 1, reason: "Dissent, injuries, debts, promises, and unresolved claims survive the watch." },
        { track: "temporal-coherence", delta: 1, reason: "Rapid authority and slow standing receive an explicit handoff relation." },
        { track: "compatibility-debt", delta: -1, reason: "One recurring private burden becomes a visible office with funding and a revision path." },
      ],
    },
  ],
  notes: {
    authority: "The Godscar Codex, Book III: The Common Ship · foundational setting bible · first recension · July 2026",
    boundary: "Private authoring seed. This is not a canonical Common Ship campaign and is not part of the current three-cartridge World release.",
  },
};
